#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Browser {{{

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

# }}}
# Editors {{{

export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

# }}}
# Language {{{

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

# }}}
# Paths {{{

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
    /usr/local/{bin,sbin}
    $HOME/.bin
    $HOME/.bin/{format,imperative,input,output,schedule}
    $HOME/.cabal/bin
    $HOME/.cargo/bin
    $path
)

# }}}
# Less {{{

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
# Do not use -F without also using -X
export LESS='-FX -i -R -w -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi
 # }}}
# Postamble (modelines) {{{
# This is specifically to allow for cool vim folding.
# Note: 'modelines' should be at least the distance
# of the modeline from the top or bottom of the file
set modeline modelines=5
# Modeline to enable marker-based folding
# vim:foldmethod=marker:
# }}}
